# ⚠️  KHÔNG commit file này lên GitHub — đã có trong .gitignore

[firebase_client]
apiKey            = "AIzaSyCJAoIA9HUcuI9lL-XvaBw3SO9RmsquNN8"
authDomain        = "my-note-app-48fc8.firebaseapp.com"
projectId         = "my-note-app-48fc8"
storageBucket     = "my-note-app-48fc8.firebasestorage.app"
messagingSenderId = "1084589177803"
appId             = "1:1084589177803:web:b2301c8142cc9838c4d44e"

[backend]
url = "https://rylan-uninformative-lisa.ngrok-free.dev"

[google_login]
client_id        = "YOUR_GOOGLE_CLIENT_ID"
redirect_uri     = "https://rylan-uninformative-lisa.ngrok-free.dev/auth/google/callback"
frontend_url     = "http://localhost:8501"
